import type { AccountData, InvoiceData } from '@/types'

export const accountsMockData: AccountData[] = [
  {
    id: '10100',
    class: 'CASHASSET',
    type: 'Asset',
    module: '',
    description: 'Petty Cash',
    currency: 'USD',
  },
  {
    id: '10200',
    class: 'CASHASSET',
    type: 'Asset',
    module: '',
    description: 'Company Checking Account - HQ',
    currency: 'USD',
  },
  {
    id: '10250',
    class: 'CASHASSET',
    type: 'Asset',
    module: '',
    description: 'Company Merchant Account',
    currency: 'USD',
  },
  {
    id: '10300',
    class: 'CASHASSET',
    type: 'Asset',
    module: '',
    description: 'Company Savings Account',
    currency: 'USD',
  },
  {
    id: '10400',
    class: 'CASHASSET',
    type: 'Asset',
    module: '',
    description: 'Undeposited Funds',
    currency: 'USD',
  },
  {
    id: '10500',
    class: 'CASHASSET',
    type: 'Asset',
    module: '',
    description: 'Cash in Transit',
    currency: 'EUR',
  },
  {
    id: '10550',
    class: 'CASHASSET',
    type: 'Asset',
    module: '',
    description: 'Cash in Transit - old',
    currency: 'USD',
  },
  {
    id: '20100',
    class: 'LIABILITY',
    type: 'Liability',
    module: 'AP',
    description: 'Accounts Payable',
    currency: 'USD',
  },
  {
    id: '20200',
    class: 'LIABILITY',
    type: 'Liability',
    module: '',
    description: 'Accrued Expenses',
    currency: 'USD',
  },
  {
    id: '30100',
    class: 'EQUITY',
    type: 'Equity',
    module: '',
    description: 'Common Stock',
    currency: 'USD',
  },
  {
    id: '40100',
    class: 'REVENUE',
    type: 'Revenue',
    module: 'AR',
    description: 'Product Sales',
    currency: 'USD',
  },
  {
    id: '50100',
    class: 'EXPENSE',
    type: 'Expense',
    module: '',
    description: 'Office Supplies',
    currency: 'USD',
  },
]

export const invoicesMockData: InvoiceData[] = [
  {
    invoice: 'INV001',
    paymentStatus: 'Paid',
    totalAmount: '$250.00',
    paymentMethod: 'Credit Card',
  },
  {
    invoice: 'INV002',
    paymentStatus: 'Pending',
    totalAmount: '$150.00',
    paymentMethod: 'PayPal',
  },
  {
    invoice: 'INV003',
    paymentStatus: 'Unpaid',
    totalAmount: '$350.00',
    paymentMethod: 'Bank Transfer',
  },
  {
    invoice: 'INV004',
    paymentStatus: 'Paid',
    totalAmount: '$450.00',
    paymentMethod: 'Credit Card',
  },
  {
    invoice: 'INV005',
    paymentStatus: 'Paid',
    totalAmount: '$550.00',
    paymentMethod: 'PayPal',
  },
  {
    invoice: 'INV006',
    paymentStatus: 'Pending',
    totalAmount: '$200.00',
    paymentMethod: 'Bank Transfer',
  },
  {
    invoice: 'INV007',
    paymentStatus: 'Unpaid',
    totalAmount: '$300.00',
    paymentMethod: 'Credit Card',
  },
]
